const data = [
  {
    title: "Cozy Beachfront Cottage",
    description: "Escape to this charming beachfront cottage for a relaxing getaway. Enjoy stunning ocean views and easy access to the beach.",
    image: { filename: "listing1", url: "https://images.unsplash.com/photo-1552733407-5d5c46c3bb3b?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=60" },
    price: 1500,
    location: "Malibu",
    country: "United States",
    type: "cottage",
    amenities: ["wifi","kitchen"],
    geometry: { type: "Point", coordinates: [-118.7798, 34.0259] },
  },
  {
    title: "Modern Loft in Downtown",
    description: "Stay in the heart of the city in this stylish loft apartment. Perfect for urban explorers!",
    image: { filename: "listing2", url: "https://images.unsplash.com/photo-1501785888041-af3ef285b470?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=60" },
    price: 1200,
    location: "New York City",
    country: "United States",
    type: "apartment",
    amenities: ["wifi","kitchen"],
    geometry: { type: "Point", coordinates: [-74.0060, 40.7128] },
  },
  {
    title: "Mountain Retreat",
    description: "Unplug and unwind in this peaceful mountain cabin. Surrounded by nature, it's a perfect place to recharge.",
    image: { filename: "listing3", url: "https://images.unsplash.com/photo-1571896349842-33c89424de2d?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=60" },
    price: 1000,
    location: "Aspen",
    country: "United States",
    type: "cabin",
    amenities: ["fireplace","kitchen"],
    geometry: { type: "Point", coordinates: [-106.8175, 39.1911] },
  },
  {
    title: "Historic Villa in Tuscany",
    description: "Experience the charm of Tuscany in this beautifully restored villa. Explore the rolling hills and vineyards.",
    image: { filename: "listing4", url: "https://images.unsplash.com/photo-1566073771259-6a8506099945?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=60" },
    price: 2500,
    location: "Florence",
    country: "Italy",
    type: "villa",
    amenities: ["pool","kitchen","wifi"],
    geometry: { type: "Point", coordinates: [11.2558, 43.7696] },
  },
  {
    title: "Secluded Treehouse Getaway",
    description: "Live among the treetops in this unique treehouse retreat. A true nature lover's paradise.",
    image: { filename: "listing5", url: "https://images.unsplash.com/photo-1520250497591-112f2f40a3f4?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=60" },
    price: 800,
    location: "Portland",
    country: "United States",
    type: "treehouse",
    amenities: ["wifi","kitchen"],
    geometry: { type: "Point", coordinates: [-122.6765, 45.5231] },
  },
  {
    title: "Beachfront Paradise",
    description: "Step out of your door onto the sandy beach. This beachfront condo offers the ultimate relaxation.",
    image: { filename: "listing6", url: "https://images.unsplash.com/photo-1571003123894-1f0594d2b5d9?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=60" },
    price: 2000,
    location: "Cancun",
    country: "Mexico",
    type: "villa",
    amenities: ["pool","wifi","kitchen"],
    geometry: { type: "Point", coordinates: [-86.8475, 21.1619] },
  },
  {
    title: "Rustic Cabin by the Lake",
    description: "Spend your days fishing and kayaking on the serene lake. This cozy cabin is perfect for outdoor enthusiasts.",
    image: { filename: "listing7", url: "https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=60" },
    price: 900,
    location: "Lake Tahoe",
    country: "United States",
    type: "cabin",
    amenities: ["fireplace","kitchen"],
    geometry: { type: "Point", coordinates: [-120.0324, 39.0968] },
  },
  {
    title: "Luxury Penthouse with City Views",
    description: "Indulge in luxury living with panoramic city views from this stunning penthouse apartment.",
    image: { filename: "listing8", url: "https://images.unsplash.com/photo-1622396481328-9b1b78cdd9fd?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=60" },
    price: 3500,
    location: "Los Angeles",
    country: "United States",
    type: "apartment",
    amenities: ["pool","wifi","kitchen"],
    geometry: { type: "Point", coordinates: [-118.2437, 34.0522] },
  },
  {
    title: "Ski-In/Ski-Out Chalet",
    description: "Hit the slopes right from your doorstep in this ski-in/ski-out chalet in the Swiss Alps.",
    image: { filename: "listing9", url: "https://images.unsplash.com/photo-1502784444187-359ac186c5bb?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=60" },
    price: 3000,
    location: "Verbier",
    country: "Switzerland",
    type: "chalet",
    amenities: ["fireplace","kitchen","wifi"],
    geometry: { type: "Point", coordinates: [7.2261, 46.0968] },
  },
  {
    title: "Safari Lodge in the Serengeti",
    description: "Experience the thrill of the wild in a comfortable safari lodge. Witness the Great Migration up close.",
    image: { filename: "listing10", url: "https://images.unsplash.com/photo-1493246507139-91e8fad9978e?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=60" },
    price: 4000,
    location: "Serengeti National Park",
    country: "Tanzania",
    type: "lodge",
    amenities: ["wifi","kitchen","pool"],
    geometry: { type: "Point", coordinates: [34.6857, -2.3333] },
  },

  // --- LISTINGS 11 TO 40 ---
  {
    title: "Historic Canal House",
    description: "Stay in a piece of history in this beautifully preserved canal house in Amsterdam's iconic district.",
    image: { filename: "listing11", url: "https://images.unsplash.com/photo-1504280390367-361c6d9f38f4?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=60" },
    price: 1800,
    location: "Amsterdam",
    country: "Netherlands",
    type: "house",
    amenities: ["wifi","kitchen"],
    geometry: { type: "Point", coordinates: [4.9041, 52.3676] },
  },
  {
    title: "Private Island Retreat",
    description: "Have an entire island to yourself for a truly exclusive and unforgettable vacation experience.",
    image: { filename: "listing12", url: "https://images.unsplash.com/photo-1618140052121-39fc6db33972?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=60" },
    price: 10000,
    location: "Fiji",
    country: "Fiji",
    type: "villa",
    amenities: ["pool","wifi","kitchen"],
    geometry: { type: "Point", coordinates: [178.0650, -17.7134] },
  },
  {
    title: "Charming Cottage in the Cotswolds",
    description: "Escape to the picturesque Cotswolds in this quaint and charming cottage with a thatched roof.",
    image: { filename: "listing13", url: "https://images.unsplash.com/photo-1602088113235-229c19758e9f?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=60" },
    price: 1200,
    location: "Cotswolds",
    country: "United Kingdom",
    type: "cottage",
    amenities: ["wifi","kitchen"],
    geometry: { type: "Point", coordinates: [-1.7832, 51.8330] },
  },
  {
    title: "Historic Brownstone in Boston",
    description: "Step back in time in this elegant historic brownstone located in the heart of Boston.",
    image: { filename: "listing14", url: "https://images.unsplash.com/photo-1533619239233-6280475a633a?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=60" },
    price: 2200,
    location: "Boston",
    country: "United States",
    type: "house",
    amenities: ["wifi","kitchen"],
    geometry: { type: "Point", coordinates: [-71.0589, 42.3601] },
  },
  {
    title: "Beachfront Bungalow in Bali",
    description: "Relax on the sandy shores of Bali in this beautiful beachfront bungalow with a private pool.",
    image: { filename: "listing15", url: "https://images.unsplash.com/photo-1602391833977-358a52198938?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=60" },
    price: 1800,
    location: "Bali",
    country: "Indonesia",
    type: "bungalow",
    amenities: ["wifi","pool","kitchen"],
    geometry: { type: "Point", coordinates: [115.1889, -8.4095] },
  },

  // Listings 16-32
  {
    title: "Urban Studio Apartment",
    description: "Compact studio apartment located in the bustling heart of Tokyo.",
    image: { filename: "listing16", url: "https://images.unsplash.com/photo-1580587771525-78b9dba3b914?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=60" },
    price: 1000,
    location: "Tokyo",
    country: "Japan",
    type: "studio",
    amenities: ["wifi","kitchen"],
    geometry: { type: "Point", coordinates: [139.6917, 35.6895] },
  },
  {
    title: "Countryside Farmhouse",
    description: "Traditional farmhouse surrounded by lush greenery, perfect for a quiet retreat.",
    image: { filename: "listing17", url: "https://images.unsplash.com/photo-1520975911761-91d569b1a2f2?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=60" },
    price: 1300,
    location: "Provence",
    country: "France",
    type: "house",
    amenities: ["wifi","kitchen","fireplace"],
    geometry: { type: "Point", coordinates: [5.0415, 43.9493] },
  },
  {
    title: "Luxury Villa in Santorini",
    description: "Stunning villa overlooking the caldera with private infinity pool.",
    image: { filename: "listing18", url: "https://images.unsplash.com/photo-1522202176988-66273c2fd55f?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=60" },
    price: 5000,
    location: "Santorini",
    country: "Greece",
    type: "villa",
    amenities: ["wifi","pool","kitchen"],
    geometry: { type: "Point", coordinates: [25.4615, 36.3932] },
  },
  {
    title: "City Apartment with Balcony",
    description: "Modern apartment with a balcony overlooking the city skyline.",
    image: { filename: "listing19", url: "https://images.unsplash.com/photo-1580587771525-78b9dba3b914?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=60" },
    price: 1200,
    location: "Paris",
    country: "France",
    type: "apartment",
    amenities: ["wifi","kitchen"],
    geometry: { type: "Point", coordinates: [2.3522, 48.8566] },
  },
  {
    title: "Luxury Mountain Lodge",
    description: "Stay at this luxurious mountain lodge with breathtaking views.",
    image: { filename: "listing20", url: "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=60" },
    price: 3500,
    location: "Aspen",
    country: "USA",
    type: "lodge",
    amenities: ["wifi","fireplace","kitchen"],
    geometry: { type: "Point", coordinates: [-106.8175, 39.1911] },
  },
  {
    title: "Seaside Villa in Portugal",
    description: "Beautiful villa with panoramic sea views in the Algarve region.",
    image: { filename: "listing21", url: "https://images.unsplash.com/photo-1571003123894-1f0594d2b5d9?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=60" },
    price: 3200,
    location: "Algarve",
    country: "Portugal",
    type: "villa",
    amenities: ["wifi","pool","kitchen"],
    geometry: { type: "Point", coordinates: [-8.2455, 37.0194] },
  },
  {
    title: "Minimalist Studio in Berlin",
    description: "Modern minimalist studio apartment in Berlin’s city center.",
    image: { filename: "listing22", url: "https://images.unsplash.com/photo-1522199710521-72d69614c702?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=60" },
    price: 900,
    location: "Berlin",
    country: "Germany",
    type: "studio",
    amenities: ["wifi","kitchen"],
    geometry: { type: "Point", coordinates: [13.4050, 52.5200] },
  },
  {
    title: "Secluded Forest Cabin",
    description: "Cozy cabin in a quiet forest location, perfect for relaxation.",
    image: { filename: "listing23", url: "https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=60" },
    price: 1100,
    location: "Black Forest",
    country: "Germany",
    type: "cabin",
    amenities: ["fireplace","wifi"],
    geometry: { type: "Point", coordinates: [8.2090, 48.0918] },
  },
  {
    title: "Charming Seaside Cottage",
    description: "Relax in this charming seaside cottage with stunning ocean views.",
    image: { filename: "listing24", url: "https://images.unsplash.com/photo-1580587771525-78b9dba3b914?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=60" },
    price: 1400,
    location: "Cornwall",
    country: "UK",
    type: "cottage",
    amenities: ["wifi","kitchen"],
    geometry: { type: "Point", coordinates: [-5.0536, 50.2660] },
  },

  // Listings 25–32
  {
    title: "Luxury Apartment Downtown",
    description: "Modern luxury apartment in downtown area.",
    image: { filename: "listing25", url: "https://images.unsplash.com/photo-1522199710521-72d69614c702?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=60" },
    price: 2700,
    location: "Tokyo",
    country: "Japan",
    type: "apartment",
    amenities: ["wifi","kitchen"],
    geometry: { type: "Point", coordinates: [139.6917, 35.6895] },
  },
  {
    title: "Eco-friendly Cabin",
    description: "Sustainable cabin in the forest.",
    image: { filename: "listing26", url: "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=60" },
    price: 1300,
    location: "Vancouver",
    country: "Canada",
    type: "cabin",
    amenities: ["wifi","fireplace"],
    geometry: { type: "Point", coordinates: [-123.1216, 49.2827] },
  },
  {
    title: "Beach Villa with Pool",
    description: "Spacious villa right on the beach with a pool.",
    image: { filename: "listing27", url: "https://images.unsplash.com/photo-1571003123894-1f0594d2b5d9?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=60" },
    price: 5000,
    location: "Ibiza",
    country: "Spain",
    type: "villa",
    amenities: ["wifi","pool","kitchen"],
    geometry: { type: "Point", coordinates: [1.4320, 38.9067] },
  },
  {
    title: "Mountain View Lodge",
    description: "Cozy lodge with stunning mountain views.",
    image: { filename: "listing28", url: "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=60" },
    price: 2200,
    location: "Denver",
    country: "USA",
    type: "lodge",
    amenities: ["wifi","fireplace"],
    geometry: { type: "Point", coordinates: [-104.9903, 39.7392] },
  },
  {
    title: "City Studio",
    description: "Compact city studio perfect for solo travelers.",
    image: { filename: "listing29", url: "https://images.unsplash.com/photo-1522199710521-72d69614c702?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=60" },
    price: 900,
    location: "Seoul",
    country: "South Korea",
    type: "studio",
    amenities: ["wifi","kitchen"],
    geometry: { type: "Point", coordinates: [126.9780, 37.5665] },
  },
  {
    title: "Seaside Cottage",
    description: "Charming cottage with ocean views.",
    image: { filename: "listing30", url: "https://images.unsplash.com/photo-1580587771525-78b9dba3b914?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=60" },
    price: 1500,
    location: "Cornwall",
    country: "UK",
    type: "cottage",
    amenities: ["wifi","kitchen"],
    geometry: { type: "Point", coordinates: [-5.0536, 50.2660] },
  },
  {
    title: "Luxury Treehouse",
    description: "Stay in this luxury treetop retreat.",
    image: { filename: "listing31", url: "https://images.unsplash.com/photo-1520250497591-112f2f40a3f4?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=60" },
    price: 2000,
    location: "Costa Rica",
    country: "Costa Rica",
    type: "treehouse",
    amenities: ["wifi","kitchen","pool"],
    geometry: { type: "Point", coordinates: [-83.7534, 9.7489] },
  },
  {
    title: "Desert Luxury Tent",
    description: "Glamorous camping experience in the desert.",
    image: { filename: "listing32", url: "https://images.unsplash.com/photo-1501004318641-b39e6451bec6?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=60" },
    price: 3000,
    location: "Marrakech",
    country: "Morocco",
    type: "tent",
    amenities: ["wifi","pool","kitchen"],
    geometry: { type: "Point", coordinates: [-7.9811, 31.6295] },
  },
  {
    title: "Luxury Apartment Downtown",
    description: "Modern luxury apartment in downtown area.",
    image: { filename: "listing33", url: "https://images.unsplash.com/photo-1522199710521-72d69614c702?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=60" },
    price: 2700,
    location: "Tokyo",
    country: "Japan",
    type: "apartment",
    amenities: ["wifi","kitchen"],
    geometry: { type: "Point", coordinates: [139.6917, 35.6895] },
  },
  {
    title: "Eco-friendly Cabin",
    description: "Sustainable cabin in the forest.",
    image: { filename: "listing34", url: "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=60" },
    price: 1300,
    location: "Vancouver",
    country: "Canada",
    type: "cabin",
    amenities: ["wifi","fireplace"],
    geometry: { type: "Point", coordinates: [-123.1216, 49.2827] },
  },
  {
    title: "Beach Villa with Pool",
    description: "Spacious villa right on the beach with a pool.",
    image: { filename: "listing35", url: "https://images.unsplash.com/photo-1571003123894-1f0594d2b5d9?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=60" },
    price: 5000,
    location: "Ibiza",
    country: "Spain",
    type: "villa",
    amenities: ["wifi","pool","kitchen"],
    geometry: { type: "Point", coordinates: [1.4320, 38.9067] },
  },
  {
    title: "Mountain View Lodge",
    description: "Cozy lodge with stunning mountain views.",
    image: { filename: "listing36", url: "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=60" },
    price: 2200,
    location: "Denver",
    country: "USA",
    type: "lodge",
    amenities: ["wifi","fireplace"],
    geometry: { type: "Point", coordinates: [-104.9903, 39.7392] },
  },
  {
    title: "City Studio",
    description: "Compact city studio perfect for solo travelers.",
    image: { filename: "listing37", url: "https://images.unsplash.com/photo-1522199710521-72d69614c702?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=60" },
    price: 900,
    location: "Seoul",
    country: "South Korea",
    type: "studio",
    amenities: ["wifi","kitchen"],
    geometry: { type: "Point", coordinates: [126.9780, 37.5665] },
  },
  {
    title: "Seaside Cottage",
    description: "Charming cottage with ocean views.",
    image: { filename: "listing38", url: "https://images.unsplash.com/photo-1580587771525-78b9dba3b914?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=60" },
    price: 1500,
    location: "Cornwall",
    country: "UK",
    type: "cottage",
    amenities: ["wifi","kitchen"],
    geometry: { type: "Point", coordinates: [-5.0536, 50.2660] },
  },
  {
    title: "Luxury Treehouse",
    description: "Stay in this luxury treetop retreat.",
    image: { filename: "listing39", url: "https://images.unsplash.com/photo-1520250497591-112f2f40a3f4?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=60" },
    price: 2000,
    location: "Costa Rica",
    country: "Costa Rica",
    type: "treehouse",
    amenities: ["wifi","kitchen","pool"],
    geometry: { type: "Point", coordinates: [-83.7534, 9.7489] },
  },
  {
    title: "Desert Luxury Tent",
    description: "Glamorous camping experience in the desert.",
    image: { filename: "listing40", url: "https://images.unsplash.com/photo-1501004318641-b39e6451bec6?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=60" },
    price: 3000,
    location: "Marrakech",
    country: "Morocco",
    type: "tent",
    amenities: ["wifi","pool","kitchen"],
    geometry: { type: "Point", coordinates: [-7.9811, 31.6295] },
  },
];

module.exports = { data };
